config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index'
  # get 'participant/:id/settle', to: 'participants#settle'

  resources :bills_participant

    resources :bills do
    collection { post :import }
  end

    resources :participants do
    collection { post :import }
  end

  root to: 'dashboard#index'
end

app/models/bills_participant.rb
# frozen_string_literal: true

class BillsParticipant < ApplicationRecord
  default_scope { order(:settled, created_at: :desc) }

  belongs_to :user, optional: true

  def bill_details
    bill = Bill.find(bill_id)
    participant = Participant.find(participant_id)

    {
       first_name: participant.first_name,
       last_name: participant.last_name,
       bill_name: bill.name,
       bill_id: bill.id,
       cost: bill.get_cost_per_participant
   }
  end
end

app/controllers/bills_participant_controller.rb
# frozen_string_literal: true

class BillsParticipantController < ApplicationController
  def index
    @bills_participant = BillsParticipant.where(:user_id => current_user.id)

    #sql caching
    # @bills_participant = BillsParticipant.all
  end

  def edit
    @participant_bill = BillsParticipant.find_by(participant_id: params[:id], bill_id: params[:bill_id])

    if @participant_bill.settled == false || @participant_bill.settled.nil?
      @participant_bill.update(settled: true)
      redirect_to bills_participant_index_path
    else
      redirect_to bills_participant_index_path
    end
  end
end

app/views/bills_participant/index.html.erb
<h3>Settle up bills</h3>

<%= render partial: "shared/buttons" %>

<table class="table table-dark">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Associated Bill</th>
    <th>Cost per person</th>
    <th>Settle up</th>
  </tr>

  <% @bills_participant.each do |bill| %>
    <tr>
      <td colspan="1"><%= bill.bill_details[:first_name] %></td>
      <td colspan="1"><%= bill.bill_details[:last_name] %></td>
      <td colspan="1"><%= bill.bill_details[:bill_name] %></td>
      <td colspan="1"><%= bill.bill_details[:cost]%></td>
      <td><%= link_to 'Settle up', edit_bills_participant_path(id: bill.participant_id, bill_id: bill.bill_id),
                      class:"btn btn-primary #{bill_settle(bill)}" , style:"width:200px" %></td>
    </tr>
  <%end %>
</table>