config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index'
  # get 'participant/:id/settle', to: 'participants#settle'

  resources :bills_participant

    resources :bills do
    collection { post :import }
  end

    resources :participants do
    collection { post :import }
  end

  root to: 'dashboard#index'
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  require 'csv'
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  default_scope { order(created_at: :desc) }

  has_and_belongs_to_many :bills

  belongs_to :user, optional: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Participant.create! row.to_hash
    end
  end

  def name_with_initial
    "Participant name: #{first_name} #{last_name}"
  end

  def cost_per_bill
    "%.2f" % self.bills.map { |b| b.get_cost_per_participant.to_f }.sum.round(2)
  end
end

app/controllers/participants_controller.rb
# frozen_string_literal: true

class ParticipantsController < ApplicationController
  def index
    # @participants = Participant.all
    @q = Participant.where(:user_id => current_user.id).ransack(params[:q])
    @participants = @q.result.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @participant = Participant.find_by_id(params[:id])
    # @bills = Bill.all
  end

  def new
    @new_participant = Participant.new
    @bills = Bill.all
    render partial: "shared/new_modal.js.erb"
  end

  def create
    @new_participant = Participant.create(participant_params.merge({user_id: current_user.id}))
    BillsParticipant.where(participant_id: @new_participant.id, user_id: nil).update_all(user_id: current_user.id)
    redirect_to participants_path
  end

  def edit
    @bills = Bill.all
    @participant = Participant.find_by_id(params[:id])
    if @participant.nil?
      redirect_to participants_path
    else
      render :edit
    end
  end

  def update
    @participant = Participant.find_by_id(params[:id])
    if @participant.nil? || @participant.update(participant_params)
      BillsParticipant.where(participant_id: @participant.id, user_id: nil).update_all(user_id: current_user.id)
      redirect_to participants_path
    else
      render :edit
    end
  end

  def destroy
    @participant = Participant.find_by_id(params[:id])
    if @participant.nil?
      redirect_to participants_path
    else
      @participant.destroy
      redirect_to participants_path
    end
  end

  def settle
    @participant = Participant.find_by_id(params[:id])
  end

  def import
    Participant.import(params[:file])
    redirect_to participants_path, notice: 'Data imported'
  end

  private

    def participant_params
      params.require(:participant).permit(:first_name, :last_name, :email, :bill_ids => [])
    end
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  def participant_error(participant)
    if participant.errors.any?
      participant.errors.full_messages.each do |msg|
        msg
      end
    end
  end

  def current_user_bills
    # Bill.where(:user_id => current_user.id)
    current_user.bills
  end
end

app/views/participants/_form.html.erb
<%= f.text_field :first_name %>
<br/>
<%= f.text_field :last_name %>
<br/>
<%= f.text_field :email %>
<br/>
<%= collection_select(:participant, :bill_ids, current_user_bills, :id, :bill_name_and_amount, {}, { :multiple => true} ) %>
<br/>

<%= f.submit "Save" %>
<%= link_to "Cancel", participants_path, class: 'btn btn-primary', style:"width:80px"%>

app/views/participants/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add new participant</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>

<div class="modal-body">
  <%= bootstrap_form_for(@new_participant) do |f| %>

    <%= render partial: "participants/form", locals: { f: f } %>

  <% end %>
</div>

app/views/participants/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Edit participant</h1>

      <%= bootstrap_form_for(@participant) do |f| %>
        
        <%# if @participant.errors.any? %>
          <%# @participant.errors.full_messages.each do |msg| %>
<!--            <li><%#= msg %></li>-->
          <%# end %>
        <%# end %>

        <%= participant_error(@participant) %>

        <%= render partial: "participants/form", locals: { f: f } %>
  
      <% end %>
    </div>
  </div>
</div>

app/views/participants/index.html.erb
<h3>Participants</h3>
<%= link_to 'Add Participants', new_participant_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>
</div>

<%= render partial: "shared/buttons" %>

<%= render partial: "shared/import", locals: { type: "participants" } %>

<%= search_form_for @q do |f| %>
  <div class="form-group"><%= f.label :first_name_cont, 'Search by First Name' %> 
  <%= f.search_field :first_name_cont %> 
  <div class="form-group"><%= f.label :last_name_cont, 'Search by Last Name' %>
  <%= f.search_field :last_name_cont %>
  </br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to "Clear", request.path, class: "btn btn-primary" %>

<table class="table table-dark">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Associated Bill</th>
    <th>Cost per bills</th>
    <th>View details</th>
    <th>Edit participant</th>
    <th>Delete participant</th>
  </tr>

  <% @participants.each do |participant| %>
    <tr>
      <td colspan="1"><%= participant.first_name %></td>
      <td colspan="1"><%= participant.last_name %></td>
      <td colspan="1"><%= participant.email %></td>
      <td colspan="1"><%= participant.bills.map { |b| b.name}.join(', ') %></td>
      <td colspan="1"><%= participant.cost_per_bill %></td>
      <td colspan="1"><%= link_to 'Participant details', participant_path(participant.id),class: 'btn btn-primary', style:"width:200px"  %></td>
      <td><%= link_to 'Edit participant', edit_participant_path(participant.id), class: 'btn btn-primary', style:"width:200px" %></td>
      <td><%= link_to 'Delete participant', participant_path(participant.id), :data => {:confirm => "Are you sure?", :method => "delete"},
              class: 'btn btn-primary', style:"width:250px"%></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @bills, list_classes: %w(pagination justify-content-end) %>

app/views/participants/show.html.erb
<h3>Participant details</h3>

<body>
  <table style="width: 300px;" class="table table-dark">
    <tr>
      <td style="width: 140px;">First Name:</td>
      <td colspan="1"><%= @participant.first_name %></td>
    </tr>
    <tr>
      <td>Last Name:</td>
      <td colspan="1"><%= @participant.last_name %>
    </tr>
    <tr>
      <td>Email:</td>
      <td colspan="1"><%= @participant.email %></td>
    </tr>
    <tr>
      <td>Associated Bill:</td>
      <td colspan="1"><%= @participant.bills.map { |b| b.name}.join(', ') %></td>
    </tr>
    <tr>
      <td>Cost per bills:</td>
      <td colspan="1"><%= @participant.cost_per_bill %></td>
    </tr>
  </table>
</body>