config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index'
  # get 'participant/:id/settle', to: 'participants#settle'

  resources :bills_participant

    resources :bills do
    collection { post :import }
  end

    resources :participants do
    collection { post :import }
  end

  root to: 'dashboard#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bill.rb
class Bill < ApplicationRecord
  require 'csv'
  validates :name, presence: true
  validates :total_amount, presence: true
  has_and_belongs_to_many :participants
  belongs_to :user, optional: true

  default_scope { order(created_at: :desc) }
  # scope :with_higher_value, ->(length = 1) { where("LENGTH(total_amount) > ?", length) }
  # scope :with_higher_value, -> { where("cost_per_person > 32") }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Bill.create! row.to_hash
    end
  end

  def bill_name_and_amount
    "#{name} bill, amount #{total_amount}"
  end

  def get_cost_per_participant
    bill_cost = if participants.present?
                  (((total_amount / participant_ids.count.to_f) * 100.0).ceil / 100.0).round(2)
                else
                  0
                end

    "%.2f" % bill_cost
  end

  def get_settled
    participants = participant_ids.count
    payed = BillsParticipant.where(bill_id: id, settled: true).count

    if payed > 0
      if payed == participants
        'total'
      else
        'partial'
      end
    else
      'unpaid'
    end
  end
end

app/models/bills_participant.rb
# frozen_string_literal: true

class BillsParticipant < ApplicationRecord
  default_scope { order(:settled, created_at: :desc) }

  belongs_to :user, optional: true

  def bill_details
    bill = Bill.find(bill_id)
    participant = Participant.find(participant_id)

    {
       first_name: participant.first_name,
       last_name: participant.last_name,
       bill_name: bill.name,
       bill_id: bill.id,
       cost: bill.get_cost_per_participant
   }
  end
end

app/models/participant.rb
# frozen_string_literal: true

class Participant < ApplicationRecord
  require 'csv'
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  default_scope { order(created_at: :desc) }

  has_and_belongs_to_many :bills

  belongs_to :user, optional: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Participant.create! row.to_hash
    end
  end

  def name_with_initial
    "Participant name: #{first_name} #{last_name}"
  end

  def cost_per_bill
    "%.2f" % self.bills.map { |b| b.get_cost_per_participant.to_f }.sum.round(2)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bills
  has_many :participants
  has_many :bills_participants
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def after_sign_out_path_for(resource_or_scope)
     login_path
   end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    # @bills = Bill.all
    @q = Bill.where(:user_id => current_user.id).ransack(params[:q])
    @bills = @q.result.paginate(:page => params[:page], :per_page => 10)
    # @bills = @q.result.page(params[:page])
  end

  def new
    @new_bill = Bill.new
    @participants = Participant.all
    render partial: "shared/new_modal.js.erb"
  end

  def create
    @new_bill = Bill.create(bill_params.merge({user_id: current_user.id}))
    BillsParticipant.where(bill_id: @new_bill.id, user_id: nil).update_all(user_id: current_user.id)
    redirect_to bills_path
  end

  def edit
    @participants = Participant.all
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil?
      redirect_to dasbills_pathhboard_path
    else
      render :edit
    end
  end

  def update
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil? || @bill.update(bill_params)
      BillsParticipant.where(bill_id: @bill.id, user_id: nil).update_all(user_id: current_user.id)
      redirect_to bills_path
    else
      render :edit
    end
  end

  def destroy
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil? 
      redirect_to bills_path
    else
      @bill.destroy
      redirect_to bills_path
    end
  end

  def import
    Bill.import(params[:file])
    redirect_to bills_path, notice: 'Data imported'
  end

  private

    def bill_params
      params.require(:bill).permit(:name, :total_amount, :description, :participant_ids => [])
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @bills = Bill.all
    @participants = Participant.all
    @bills_participant = BillsParticipant.all
  end

  def new
    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  
  
end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def destroy
    super
     # redirect_to login_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bills_helper.rb
module BillsHelper
  def bill_error(bill)
    if bill.errors.any?
      bill.errors.full_messages.each do |msg|
        msg
      end
    end
  end

  def current_user_participants
    # Participant.where(:user_id => current_user.id)
    current_user.participants
  end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/participant_views_helper.rb
module ParticipantViewsHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
  def participant_error(participant)
    if participant.errors.any?
      participant.errors.full_messages.each do |msg|
        msg
      end
    end
  end

  def current_user_bills
    # Bill.where(:user_id => current_user.id)
    current_user.bills
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/settle_helper.rb
module SettleHelper
  def bill_settle(bill)
    'disabled' if bill.settled?
  end
end

app/helpers/users_invitations_helper.rb
module UsersInvitationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoneySettlingTool</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= render partial: "shared/nav" %>

  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    
    <%# <%= render partial: "shared/dashboard_content" if current_page?(root_path) %>

  </body>
</html>

app/views/shared/_buttons.html.erb
<div style="float:right">
  <% if current_page?(bills_path) %>
    <%= link_to 'Participants', participants_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Settled bills', bills_participant_index_path, class: 'btn btn-primary btn-lg' %>
  <% elsif current_page?(participants_path) %>
    <%= link_to 'Bills', bills_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Settled bills', bills_participant_index_path, class: 'btn btn-primary btn-lg' %>
  <% elsif current_page?(bills_participant_index_path) %>
    <%= link_to 'Participants', participants_path, class: 'btn btn-primary btn-lg' %>
    <%= link_to 'Bills', bills_path, class: 'btn btn-primary btn-lg' %>
  <% end %>
</div>

app/views/shared/_content_index.erb
<%= content_tag(:h1, "Dashboard", class: "text-danger") %>
<%= link_to "Send invitation", new_user_invitation_path, class: 'btn btn-secondary col-2' %>
</br>
<%= render partial: "shared/dashboard_content"%>

app/views/shared/_dashboard_content.erb
</br>
<body>
  <%# <%= image_tag "money.jpg" %>
  <div>
    <%= video_tag( 'countmoney.mp4', id: 'background', autoplay: true, loop: true, muted: true )%>
  </div>
</body>

app/views/shared/_import.html.erb
<div class="my-5 mx-auto">
  <%= form_tag({:controller => type, :action => "import"}, :method => "post", multipart: true) do %>
    <%= file_field_tag :file, accept: 'text/csv', required: true %>
    <%= submit_tag "Import #{type}"%>
  <% end %>
</div>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-light bg-light">
  <%= link_to "Money Tool", root_path, class: "navbar-brand" %>
  <div class="form-inline">
    <div style="padding-left: 10px;">

      <% if user_signed_in? %>
        <%= link_to "Sign Out", signout_path, class: "btn btn-outline-warning", role: "button" %>
        <%# <%= link_to_unless_current "Dashboard", dashboard_path, class: "btn btn-outline-info", role: "button" do  %>
          <%# # link_to "Home", root_path, class: "btn btn-outline-info", role: "button" %>
          <%# # end %>
        <p><%= current_user.email %></p>
        <p>User name: <%= current_user.name %></p>
      <% else %>
        <%= link_to "Log in", login_path, class: "btn btn-outline-primary", role: "button" %>
        <%= link_to "Sign Up", signup_path, class: "btn btn-outline-success", role: "button" %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_new_modal.js.erb
$("#modal-window").find(".modal-content").html("<%= j (render 'new') %>");
$("#modal-window").modal('show');