config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'signup', to: 'devise/registrations#new'
    get 'signout', to: 'sessions#destroy'
  end

  get 'dashboard', to: 'dashboard#index'
  # get 'participant/:id/settle', to: 'participants#settle'

  resources :bills_participant

    resources :bills do
    collection { post :import }
  end

    resources :participants do
    collection { post :import }
  end

  root to: 'dashboard#index'
end

app/models/bill.rb
class Bill < ApplicationRecord
  require 'csv'
  validates :name, presence: true
  validates :total_amount, presence: true
  has_and_belongs_to_many :participants
  belongs_to :user, optional: true

  default_scope { order(created_at: :desc) }
  # scope :with_higher_value, ->(length = 1) { where("LENGTH(total_amount) > ?", length) }
  # scope :with_higher_value, -> { where("cost_per_person > 32") }

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Bill.create! row.to_hash
    end
  end

  def bill_name_and_amount
    "#{name} bill, amount #{total_amount}"
  end

  def get_cost_per_participant
    bill_cost = if participants.present?
                  (((total_amount / participant_ids.count.to_f) * 100.0).ceil / 100.0).round(2)
                else
                  0
                end

    "%.2f" % bill_cost
  end

  def get_settled
    participants = participant_ids.count
    payed = BillsParticipant.where(bill_id: id, settled: true).count

    if payed > 0
      if payed == participants
        'total'
      else
        'partial'
      end
    else
      'unpaid'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :bills
  has_many :participants
  has_many :bills_participants
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:update]

  def index
    # @bills = Bill.all
    @q = Bill.where(:user_id => current_user.id).ransack(params[:q])
    @bills = @q.result.paginate(:page => params[:page], :per_page => 10)
    # @bills = @q.result.page(params[:page])
  end

  def new
    @new_bill = Bill.new
    @participants = Participant.all
    render partial: "shared/new_modal.js.erb"
  end

  def create
    @new_bill = Bill.create(bill_params.merge({user_id: current_user.id}))
    BillsParticipant.where(bill_id: @new_bill.id, user_id: nil).update_all(user_id: current_user.id)
    redirect_to bills_path
  end

  def edit
    @participants = Participant.all
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil?
      redirect_to dasbills_pathhboard_path
    else
      render :edit
    end
  end

  def update
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil? || @bill.update(bill_params)
      BillsParticipant.where(bill_id: @bill.id, user_id: nil).update_all(user_id: current_user.id)
      redirect_to bills_path
    else
      render :edit
    end
  end

  def destroy
    @bill = Bill.find_by_id(params[:id])
    if @bill.nil? 
      redirect_to bills_path
    else
      @bill.destroy
      redirect_to bills_path
    end
  end

  def import
    Bill.import(params[:file])
    redirect_to bills_path, notice: 'Data imported'
  end

  private

    def bill_params
      params.require(:bill).permit(:name, :total_amount, :description, :participant_ids => [])
    end
end

app/helpers/bills_helper.rb
module BillsHelper
  def bill_error(bill)
    if bill.errors.any?
      bill.errors.full_messages.each do |msg|
        msg
      end
    end
  end

  def current_user_participants
    # Participant.where(:user_id => current_user.id)
    current_user.participants
  end
end

app/views/bills/_form.html.erb
<%= f.text_field :name %>
<br/>
<%= f.text_field :total_amount, append: "RON"  %>
<br/>
<%= f.text_area :description %>
<br/>
<%= f.label :participants %>
<br/>
<%= f.select(:participant_ids, options_from_collection_for_select(current_user_participants, :id, :name_with_initial, f.object.participant_ids), {}, { :multiple => true}) %>
<br/>
<%= f.submit "Save" %>
<%= link_to "Cancel", bills_path, class: 'btn btn-primary', style:"width:80px" %>

app/views/bills/_new.html.erb
<div class="modal-header">
  <h4 class="modal-title" id="myModalLabel">Add new bill</h4>
  <button type="button" class="close" data-dismiss="modal">x</button>
</div>

<div class="modal-body">
  <%= bootstrap_form_for(@new_bill) do |f| %>

    <%= render partial: "bills/form", locals: { f: f } %>

  <% end %>
</div>

app/views/bills/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Edit bill</h1>

      <%= bootstrap_form_for @bill do |f| %>

        <%# if @bill.errors.any? %>
          <%# @bill.errors.full_messages.each do |msg| %>
<!--            <li><%#= msg %></li>-->
          <%# end %>
        <%# end %>

        <%= bill_error(@bill) %>

        <%= render partial: "bills/form", locals: { f: f } %>

      <% end %>
    </div>
  </div>
</div>

app/views/bills/index.html.erb
<h3>Bills</h3>
<%= link_to 'Add bill', new_bill_path, {:remote => true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window', class: 'btn btn-primary btn-lg'}  %>
  <div id="modal-window" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content"></div>
    </div>
  </div>

<%= render partial: "shared/buttons" %>

<%= render partial: "shared/import", locals: { type: "bills" }%>

<%= search_form_for @q do |f| %>
  <div class="form-group"><%= f.label :name_cont, 'Search by Bill Name' %> 
  <%= f.search_field :name_cont %> 
  <div class="form-group"><%= f.label :total_amount_eq, 'Search by Total Amount' %>
  <%= f.search_field :total_amount_eq %>
  </br>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>
<%= link_to "Clear", request.path, class: "btn btn-primary" %>

<table class="table table-dark">
  <tr>
    <th><%= sort_link(@q, :name) %></th>
    <th><%= sort_link(@q, :total_amount) %></th>
    <th>Description</th>
    <th>Associated Participant</th>
    <th><%= sort_link(@q, :get_cost_per_participant) %></th>
    <th>Settled</th>
    <th>Edit bill</th>
    <th>Delete bill</th>
  </tr>

  <% @bills.each do |bill| %>
    <tr>
      <td colspan="1"><%= bill.name %></td>
      <td colspan="1"><%= bill.total_amount %></td>
      <td colspan="1"><%= bill.description %></td>
      <td colspan="1"><%= bill.participants.map {|p| p.first_name}.join(', ') %></td>
      <td colspan="1"><%= bill.get_cost_per_participant %></td>
      <td colspan="1"><%= bill.get_settled %> </td>
      <td><%= link_to 'Edit bill', edit_bill_path(bill.id), class: 'btn btn-primary', style:"width:200px" %></td>
      <td><%= link_to 'Delete bill', bill_path(bill.id), :data => {:confirm => "Are you sure?", :method => "delete"},
                                                          class: 'btn btn-primary', style:"width:250px"%></td>
    </tr>
  <% end %>
</table>

<%= will_paginate @bills, list_classes: %w(pagination justify-content-end) %>